name: final
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - monai=1.3.2
  - numpy=1.26.4
  - nibabel=5.2.1
  - jupyter
  - matplotlib
  - tqdm
  - tensorboard
  - tensorboardx
  - einops
  - gdown
